version: "3.9"
services:
  db:
    image: "postgres:15"
    container_name: "goVote"
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - goVote:/var/lib/postgresql/data
volumes:
  goVote:
